version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always

  backend:
    build:
      context: ./backend
    restart: always
    environment:
      DATABASE_URL: postgres://user:password@db/task_management
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    restart: always

volumes:
  postgres_data: